#!/usr/bin/env python3
"""
Competitor Intelligence Report Generator
Clean, production-grade report generation for Obsidian + Discord.
"""

import sqlite3
from datetime import datetime
from pathlib import Path
import logging
logger = logging.getLogger(__name__)

DB_PATH = Path.home() / ".hermes" / "agents" / "competitor_intel" / "competitor_intel.db"
REPORTS_DIR = Path.home() / ".hermes" / "agents" / "competitor_intel" / "reports"

REPORTS_DIR.mkdir(parents=True, exist_ok=True)


def get_top_events(limit=15):
    """Retrieve top intelligence events by amount."""
    conn = sqlite3.connect(DB_PATH)
    cur = conn.cursor()
    cur.execute("""
        SELECT event_type, round_type, amount_usd, lead_investor, 
               is_rumor, announced_date, source
        FROM intelligence_events
        ORDER BY CASE WHEN amount_usd IS NULL THEN 1 ELSE 0 END, amount_usd DESC, announced_date DESC
        LIMIT ?
    """, (limit,))
    rows = cur.fetchall()
    conn.close()
    return rows


def get_top_companies(limit=10):
    """Retrieve top companies by score."""
    conn = sqlite3.connect(DB_PATH)
    cur = conn.cursor()
    cur.execute("""
        SELECT name, score, industry, github_stars
        FROM companies
        ORDER BY CASE WHEN score IS NULL THEN 1 ELSE 0 END, score DESC, github_stars DESC
        LIMIT ?
    """, (limit,))
    rows = cur.fetchall()
    conn.close()
    return rows


def format_amount(amount):
    """Format USD amount in human-readable form (B/M/K)."""
    if not amount:
        return "Undisclosed"
    if amount >= 1_000_000_000:
        return f"${amount / 1_000_000_000:.1f}B"
    if amount >= 1_000_000:
        return f"${amount / 1_000_000:.0f}M"
    return f"${amount:,}"


def get_stats():
    """Return basic counts of events and companies."""
    conn = sqlite3.connect(DB_PATH)
    cur = conn.cursor()
    cur.execute("SELECT COUNT(*) FROM intelligence_events")
    events = cur.fetchone()[0]
    cur.execute("SELECT COUNT(*) FROM companies")
    companies = cur.fetchone()[0]
    conn.close()
    return events, companies


def generate_discord_report():
    """Generate a Discord-friendly text report."""
    events = get_top_events(12)
    companies = get_top_companies(8)
    event_count, company_count = get_stats()
    now = datetime.now().strftime("%B %d, %Y")

    lines = [f"# Competitor Intelligence Brief — {now}", "", "## Largest Recent Funding Events"]

    for event in events:
        etype, rtype, amount, investor, rumor, date, source = event
        amt = format_amount(amount)
        tag = "Rumor" if rumor else "Confirmed"
        inv = f" • {investor}" if investor else ""
        lines.append(f"- **{amt}** {rtype or ''} — {tag}{inv}")
        lines.append(f"  *{source}* ({date or 'recent'})")

    lines.append("")
    lines.append("## Top Tracked Companies")

    for name, score, industry, stars in companies:
        score_str = f" (Score: {score:.1f})" if score else ""
        gh = f" • ⭐ {stars:,}" if stars else ""
        lines.append(f"- **{name}**{score_str}{gh}")

    lines.append(f"\n*Generated {now} • {event_count} events • {company_count} companies*")
    return "\n".join(lines)


def generate_obsidian_note():
    """Generate an Obsidian-compatible Markdown note."""
    events = get_top_events(20)
    companies = get_top_companies(12)
    date_str = datetime.now().strftime("%Y-%m-%d")
    filename = f"Competitor Intel - {date_str}.md"

    lines = [
        "---",
        "tags: [competitor-intel, funding, daily-brief]",
        f"date: {date_str}",
        "---",
        "",
        f"# Competitor Intelligence — {datetime.now().strftime('%B %d, %Y')}",
        "",
        "## Key Funding Events",
        ""
    ]

    for event in events:
        etype, rtype, amount, investor, rumor, date, source = event
        amt = format_amount(amount)
        tag = " **Rumor**" if rumor else ""
        inv = f" — {investor}" if investor else ""
        lines.append(f"- **{amt}** {rtype or 'Round'}{tag}{inv}")
        lines.append(f"  *Source: {source}*")

    lines.append("")
    lines.append("## Top Companies")

    for name, score, industry, stars in companies:
        score_str = f" (Score: {score or 0:.1f})" if score else ""
        lines.append(f"- [[{name}]]{score_str}")

    lines.append("")
    lines.append("---")
    lines.append("*Auto-generated by Hermes Competitor Intelligence*")

    content = "\n".join(lines)

    # Save to local reports folder (portable)
    report_path = REPORTS_DIR / filename
    report_path.write_text(content)

    return report_path


if __name__ == "__main__":
    discord_report = generate_discord_report()
    obsidian_path = generate_obsidian_note()

    logger.info("Reports generated: Discord brief ready, Obsidian note: %s", obsidian_path)