"""
Obsidian Note Generator for Competitor Intelligence
Creates rich, linked Markdown notes for companies.
"""

import json
import logging
from datetime import datetime
from pathlib import Path

from embeddings import cosine_similarity

logger = logging.getLogger("obsidian_notes")

from db.connection import get_conn
from db.funding_read import fetch_company_funding_rows

OBSIDIAN_VAULT = Path.home() / "Obsidian" / "Competitor Intelligence" / "Companies"
OBSIDIAN_VAULT.mkdir(parents=True, exist_ok=True)


def get_similar_companies(company_id: int, limit: int = 5):
    """Find similar companies using embedding cosine similarity."""

    conn = get_conn()
    cursor = conn.cursor()
    cursor.execute("SELECT embedding FROM companies WHERE id = ?", (company_id,))
    row = cursor.fetchone()
    if not row or not row["embedding"]:
        return []

    target_emb = json.loads(row["embedding"])

    cursor.execute(
        """
        SELECT id, name, embedding
        FROM companies
        WHERE id != ? AND embedding IS NOT NULL
        """,
        (company_id,),
    )

    similarities = []
    for row in cursor.fetchall():
        try:
            emb = json.loads(row["embedding"])
            score = cosine_similarity(target_emb, emb)
            similarities.append((row["name"], score))
        except (json.JSONDecodeError, TypeError, ValueError):
            continue

    similarities.sort(key=lambda x: x[1], reverse=True)
    conn.close()
    return similarities[:limit]


def generate_note(company_id: int, name: str, description: str, score: float) -> Path:
    """Generate a full Obsidian note for one company."""
    conn = get_conn()
    cursor = conn.cursor()

    funding = fetch_company_funding_rows(cursor, company_id)
    conn.close()

    # Get similar companies
    similar = get_similar_companies(company_id)

    # Build note
    lines = []
    lines.append(f"# {name}")
    lines.append(
        f"\n**Score**: {score:.3f}  |  **Last Updated**: {datetime.now().strftime('%Y-%m-%d')}"
    )
    lines.append(f"\n## Overview\n{description or 'No description available.'}")

    if funding:
        lines.append("\n## Funding History")
        for f in funding:
            val = f" (Valuation: ${f['valuation_usd']:,})" if f["valuation_usd"] else ""
            lead = f" — led by {f['lead_investor']}" if f["lead_investor"] else ""
            amount = f["amount_usd"]
            amount_str = f"${amount:,}" if amount else "undisclosed"
            lines.append(
                f"- **{f['round_type']}** — {amount_str}{val}{lead} ({f['announced_date']})"
            )

    if similar:
        lines.append("\n## Similar Companies")
        for s_name, s_score in similar:
            lines.append(f"- [[{s_name}]] (similarity: {s_score:.2f})")

    lines.append("\n## Tags")
    lines.append("#competitor #ai #startup")
    lines.append("\n---\n*Generated by Hermes Competitor Intelligence Agent*")

    # Save note
    safe_name = name.replace("/", "-").replace(":", "")
    filepath = OBSIDIAN_VAULT / f"{safe_name}.md"
    filepath.write_text("\n".join(lines), encoding="utf-8")
    logger.info("Created: %s.md", safe_name)
    return filepath


def generate_all_notes(limit: int = 20) -> int:
    """Generate Obsidian notes for the top N companies."""
    logger.info("Generating Obsidian notes for top %s companies...", limit)
    conn = get_conn()
    cursor = conn.cursor()
    cursor.execute(
        """
        SELECT id, name, description, score
        FROM companies
        WHERE score IS NOT NULL
        ORDER BY score DESC
        LIMIT ?
        """,
        (limit,),
    )
    rows = cursor.fetchall()
    conn.close()

    for row in rows:
        try:
            generate_note(row["id"], row["name"], row["description"], row["score"])
        except Exception as e:
            logger.error("Failed to generate note for %s: %s", row["name"], e)

    logger.info("Generated %s Obsidian notes in: %s", len(rows), OBSIDIAN_VAULT)
    return len(rows)


if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO, format="%(levelname)s: %(message)s")
    generate_all_notes(20)
