"""Obsidian vault report generator."""

from datetime import datetime
from pathlib import Path
from typing import Any

import structlog
from jinja2 import Template

from competitor_intel.db.models import Company, FundingEvent
from competitor_intel.db.session import get_session
from competitor_intel.settings import get_settings

logger = structlog.get_logger()


COMPANY_NOTE_TEMPLATE = """# {{ company.name }}

> {{ company.description or "No description available" }}

## Overview
- **Industry**: {{ company.industry }}
- **Website**: {{ company.website or "N/A" }}
- **GitHub**: {{ company.github_org or "N/A" }}
- **X/Twitter**: {{ company.x_handle or "N/A" }}
{% if company.score %}- **Score**: {{ "%.1f" | format(company.score * 100) }}%{% endif %}
- **Last Updated**: {{ now.strftime('%Y-%m-%d') }}

## Funding History
{% if funding_events %}
{% for event in funding_events %}
- **{{ event.announced_date or "Date unknown" }}** — {{ event.round_type or "Unknown round" }}
  {%- if event.amount_usd %} (${{ "{:,}".format(event.amount_usd) }}){% endif %}
  {%- if event.lead_investor %} — led by {{ event.lead_investor }}{% endif %}
{% endfor %}
{% else %}
_No funding events recorded._
{% endif %}

## Tags
#competitor #{{ company.industry.lower().replace('/', '-').replace(' ', '-') }}

---
*Generated by Competitor Intelligence Agent*
"""


class ObsidianReporter:
    """Generate Obsidian-compatible Markdown notes.
    
    Creates structured notes for each tracked company with:
    - Company overview
    - Funding history
    - Links to other companies
    - Proper Obsidian tags
    """
    
    def __init__(self):
        self.settings = get_settings()
        self.template = Template(COMPANY_NOTE_TEMPLATE)
    
    def generate_company_note(self, company_id: int) -> str | None:
        """Generate a note for a single company."""
        with get_session() as session:
            company = session.query(Company).get(company_id)
            if not company:
                return None
            
            funding_events = session.query(FundingEvent).filter(
                FundingEvent.company_id == company_id
            ).order_by(FundingEvent.announced_date.desc()).all()
        
        return self.template.render(
            company=company,
            funding_events=funding_events,
            now=datetime.now(),
        )
    
    def generate_all_notes(self, limit: int = 50) -> list[Path]:
        """Generate notes for all tracked companies."""
        vault_dir = self.settings.obsidian_dir / "Companies"
        vault_dir.mkdir(parents=True, exist_ok=True)
        
        with get_session() as session:
            companies = session.query(Company).order_by(
                Company.score.desc().nulls_last()
            ).limit(limit).all()
        
        generated = []
        for company in companies:
            try:
                note = self.generate_company_note(company.id)
                if not note:
                    continue
                
                # Sanitize filename
                safe_name = self._sanitize_filename(company.name)
                filepath = vault_dir / f"{safe_name}.md"
                
                filepath.write_text(note, encoding="utf-8")
                generated.append(filepath)
                
                logger.debug("obsidian_note_generated", company=company.name)
                
            except Exception as e:
                logger.error(
                    "obsidian_note_error",
                    company=company.name,
                    error=str(e),
                )
        
        logger.info("obsidian_generation_complete", count=len(generated))
        return generated
    
    def generate_index(self) -> str:
        """Generate an index note linking all companies."""
        with get_session() as session:
            companies = session.query(Company).order_by(Company.name).all()
        
        lines = [
            "# Competitor Intelligence Index",
            "",
            f"**Generated**: {datetime.now().strftime('%Y-%m-%d')}",
            f"**Companies tracked**: {len(companies)}",
            "",
            "## All Companies",
            "",
        ]
        
        for company in companies:
            safe_name = self._sanitize_filename(company.name)
            score_text = f" (Score: {company.score:.2f})" if company.score else ""
            lines.append(f"- [[{safe_name}]]{score_text}")
        
        return "\n".join(lines)
    
    @staticmethod
    def _sanitize_filename(name: str) -> str:
        """Sanitize company name for use as filename."""
        return name.replace(" ", "_").replace("/", "-").replace(":", "")
